name: Build LLVM (Bionic)
run-name: Build LLVM for r${{inputs.version}}${{inputs.revision}} ${{inputs.projects}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "NDK Release version:"
        default: "30"
        required: true
      revision:
        description: "NDK Release revision:"
        required: false
        type: string
      projects:
        description: "Projects to build:"
        # bolt;clang;clang-tools-extra;compiler-rt;cross-project-tests;libc;libclc;lld;lldb;mlir;openmp;polly;pstl;flang
        default: "bolt;clang;clang-tools-extra;lld;polly"
        required: true
      pgo:
        description: "Use published PGO profile"
        default: true
        required: false
        type: boolean
      mlgo:
        description: "Embed the arm64 MLGO models"
        default: true
        required: false
        type: boolean
      lto:
        description: "Use ThinLTO"
        default: true
        required: false
        type: boolean
      only:
        description: "Only these targets (JSON array), default all"
        required: false
        type: string

permissions:
  contents: write
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build-llvm.yml
    secrets: inherit
    with:
      platform: bionic
      version: ${{ inputs.version }}
      revision: ${{ inputs.revision }}
      projects: ${{ inputs.projects }}
      pgo: ${{ inputs.pgo }}
      mlgo: ${{ inputs.mlgo }}
      lto: ${{ inputs.lto }}
      only: ${{ inputs.only }}
      # riscv64-linux-android
      targets: '["aarch64-linux-android", "armv7a-linux-androideabi", "i686-linux-android", "x86_64-linux-android"]'
