name: Build LLVM (BSD)
run-name: Build LLVM for r${{inputs.version}}${{inputs.revision}} ${{inputs.projects}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "NDK Release version:"
        default: "30"
        required: true
      revision:
        description: "NDK Release revision:"
        required: false
        type: string
      projects:
        description: "Projects to build:"
        # bolt;clang;clang-tools-extra;compiler-rt;cross-project-tests;libc;libclc;lld;lldb;mlir;openmp;polly;pstl;flang
        default: "bolt;clang;clang-tools-extra;lld;polly"
        required: true
      pgo:
        description: "Use published PGO profile"
        default: true
        required: false
        type: boolean
      mlgo:
        description: "Embed the arm64 MLGO models"
        default: true
        required: false
        type: boolean
      lto:
        description: "Use ThinLTO"
        default: true
        required: false
        type: boolean
      only:
        description: "Only these targets (JSON array), default all"
        required: false
        type: string

permissions:
  contents: write
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build-llvm.yml
    secrets: inherit
    with:
      platform: bsd
      version: ${{ inputs.version }}
      revision: ${{ inputs.revision }}
      projects: ${{ inputs.projects }}
      pgo: ${{ inputs.pgo }}
      mlgo: ${{ inputs.mlgo }}
      lto: ${{ inputs.lto }}
      only: ${{ inputs.only }}
      # powerpc-netbsd-eabi, powerpc-freebsd-eabihf
      targets: >-
        ["aarch64-freebsd-none", "aarch64-netbsd-none", "aarch64-openbsd-none",
         "aarch64_be-netbsd-none", "arm-freebsd-eabihf", "arm-netbsd-eabi",
         "arm-netbsd-eabihf", "armeb-netbsd-eabi", "armeb-netbsd-eabihf",
         "mips-netbsd-eabi", "mips-netbsd-eabihf", "mipsel-netbsd-eabi",
         "mipsel-netbsd-eabihf", "mips64el-openbsd-none", "mips64-openbsd-none",
         "powerpc-netbsd-eabihf", "powerpc64-freebsd-none", "powerpc64-openbsd-none",
         "powerpc64le-freebsd-none", "riscv64-freebsd-none", "x86-freebsd-none",
         "x86-netbsd-none", "x86_64-freebsd-none", "x86_64-netbsd-none",
         "arm-openbsd-eabi", "powerpc-openbsd-eabihf", "riscv64-openbsd-none",
         "x86-openbsd-none", "x86_64-openbsd-none", "riscv32-netbsd-none",
         "riscv64-netbsd-none"]
